name: k8s-tew
on_project_start: export PATH=$(pwd):$PATH

windows:
  - editor:
      layout: main-horizontal
      panes:
        - vi
        - make watch-and-compile
  - shell:
  - sandbox-command:
      - cd setup/sandbox/vbox-single
  - sandbox-environment:
      - cd setup/sandbox/vbox-single
      - source <(k8s-tew environment)
  - k9s:
      - cd setup/sandbox/vbox-single
      - source <(k8s-tew environment)
      - k9s
  - documentation-update:
      - make watch-and-update-documentation 
  - documentation-server:
      - (cd docs/_build/html && python -m SimpleHTTPServer 8080)
  - port-forwarding-80:
      - make forward-80
  - port-forwarding-443:
      - make forward-443
